version: '3'

services:
  redis:
    image: redis:6.2.6-alpine
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data
    restart: always

  pg:
    image: postgres:12.13-alpine
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    restart: always

  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/home/web/app'
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    links:
      - pg
    depends_on:
      - pg
    entrypoint: ./bin/dockerize -wait tcp://pg:5432 -timeout 60s
    command: python Test/manage.py runserver 0.0.0.0:8000
    restart: always

  dramatiq-app:
    <<: *app
    ports: [ ]
    command: bash -c "cd Test && python manage.py rundramatiq"
    restart: always



