# Generated by Django 4.2.8 on 2023-12-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('surname', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(db_index=True, max_length=1000, unique=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user_registration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('status_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UsersFiles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=1000)),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.roles'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainApp.userstatus'),
        ),
    ]
